from django import forms

class NewOrder (forms.Form):    
    dominio = forms.CharField(min_length=6, max_length=10)    
    chasis = forms.CharField(max_length=25)
    marca_vehiculo = forms.CharField(max_length=20)
    modelo_vehiculo = forms.CharField(max_length=20)
    ano_vehiculo = forms.IntegerField()
    operador = forms.CharField(max_length=30)
    cuit = forms.CharField(max_length=11)
    marca_tacografo = forms.CharField(max_length=20)
    modelo_tacografo = forms.CharField(max_length=20)
    sn = forms.CharField(max_length=26)
    factor_k = forms.CharField(max_length=6)
    rodado = forms.CharField(max_length=16,required=False)
    limite_v = forms.CharField(max_length=10,required=False)
    fecha = forms.DateField(required=False)
    ot = forms.CharField(required=False)

class EditOrder (forms.Form):    
    dominio = forms.CharField(min_length=6, max_length=10)    
    chasis = forms.CharField(max_length=25)
    marca_vehiculo = forms.CharField(max_length=20)
    modelo_vehiculo = forms.CharField(max_length=20)
    ano_vehiculo = forms.IntegerField()
    operador = forms.CharField(max_length=30)
    cuit = forms.CharField(max_length=11)
    marca_tacografo = forms.CharField(max_length=20)
    modelo_tacografo = forms.CharField(max_length=20)
    sn = forms.CharField(max_length=26)
    factor_k = forms.CharField(max_length=6)
    rodado = forms.CharField(max_length=16,required=False)
    limite_v = forms.CharField(max_length=10,required=False)
    fecha = forms.DateField(required=False)
    ot = forms.CharField(required=False)