# Generated by Django 4.1.1 on 2024-12-05 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=30)),
                ('contrasena', models.CharField(max_length=30)),
                ('agente', models.CharField(max_length=5)),
                ('razon_social', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=100)),
                ('localidad', models.CharField(max_length=60)),
                ('provincia', models.CharField(max_length=60)),
                ('pais', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=100)),
                ('tel1', models.IntegerField()),
                ('tel2', models.IntegerField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
