# Generated by Django 4.1.1 on 2024-12-11 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_provincia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tel2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
