# Generated by Django 4.1.1 on 2024-12-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_profile_tel2'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='responsable',
            field=models.CharField(default='null', max_length=40),
            preserve_default=False,
        ),
    ]
