# Generated by Django 4.1.1 on 2024-12-11 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_order_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='limite_v',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='orden',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ot',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='rodado',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
