# Generated by Django 4.1.1 on 2024-12-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_alter_order_fecha_alter_order_limite_v_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='modelo_tacografo',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
    ]
