# Generated by Django 4.1.1 on 2024-12-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='puesto',
            field=models.CharField(default='null', max_length=40),
            preserve_default=False,
        ),
    ]
